//! Phase G.5 PAFF corpus validation (todo-h264.md).
//!
//! Decodes a PAFF bitstream (generated by the JM reference encoder, since
//! x264 cannot produce PAFF) and compares against ffmpeg's reference decode.
//! Validates the `decode_interlaced_b_field` and field-coordinate bi-predictive
//! MC path.
//!
//! The test fixture is a short IP sequence encoded with `PicInterlace=1`
//! (field coding): an IDR top-field followed by P top/bottom fields. ffmpeg
//! outputs 2 frames in display order (IDR, P); the decoder should match.

use std::process::Command;

use tpt_kinetix_core::packet::Packet;
use tpt_kinetix_core::timestamp::Timestamp;
use tpt_kinetix_h264::H264Decoder;

fn ffmpeg_available() -> bool {
    Command::new("ffmpeg")
        .arg("-version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn compare(a: &[u8], b: &[u8]) -> (i32, usize, usize) {
    let n = a.len().min(b.len());
    let mut max_diff = 0i32;
    let mut num_diff = 0usize;
    for i in 0..n {
        let d = (a[i] as i32 - b[i] as i32).abs();
        if d != 0 {
            num_diff += 1;
            max_diff = max_diff.max(d);
        }
    }
    (max_diff, num_diff, n)
}

fn make_packet(data: Vec<u8>, pts: i64) -> Packet {
    Packet {
        pts: Timestamp::new(pts, (1, 30)),
        dts: Timestamp::new(pts, (1, 30)),
        data,
        stream_index: 0,
        is_key_frame: true,
    }
}

#[test]
fn paff_b_field_decode() {
    if !ffmpeg_available() {
        eprintln!("paff_b_field_decode: skipped (ffmpeg unavailable)");
        return;
    }

    let skip_db = std::env::var("BFIELD_SKIP_DEBLOCK").is_ok();
    if skip_db {
        unsafe { std::env::set_var("KINETIX_SKIP_DEBLOCK", "1") };
    }
    let dir = std::env::temp_dir().join("dbg_paff_b_field");
    std::fs::create_dir_all(&dir).unwrap();

    let h264_path = dir.join("paff_b.h264");
    let ref_path = dir.join("paff_b_ref.yuv");

    // Copy the pre-generated PAFF bitstream into place.
    let src = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("paff_b_field.264");
    if !src.exists() {
        eprintln!("paff_b_field_decode: fixture not found at {src:?}");
        return;
    }
    std::fs::copy(&src, &h264_path).unwrap();

    // Reference decode with ffmpeg (full decode including deblocking).
    let mut args: Vec<&str> = vec!["-hide_banner", "-loglevel", "error", "-y"];
    if skip_db {
        args.push("-skip_loop_filter");
        args.push("all");
    }
    args.extend([
        "-i",
        h264_path.to_str().unwrap(),
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p",
        ref_path.to_str().unwrap(),
    ]);
    let ok = Command::new("ffmpeg").args(&args).output().unwrap();
    assert!(ok.status.success(), "ffmpeg ref decode failed");
    let ref_yuv = std::fs::read(&ref_path).unwrap();
    let frame_len = 80 * 64 * 3 / 2;
    let ref_frames = ref_yuv.len() / frame_len;
    println!("ref_yuv: {} bytes ({} frames)", ref_yuv.len(), ref_frames);

    let annexb = std::fs::read(&h264_path).unwrap();

    // Feed the whole Annex B stream as a single packet.
    let mut dec = H264Decoder::new();
    let pkt = make_packet(annexb, 0);
    let mut frames = Vec::new();

    let empty = make_packet(Vec::new(), 0);
    let mut first = true;
    loop {
        let p = if first { &pkt } else { &empty };
        first = false;
        match dec.decode(p) {
            Ok(Some(f)) => {
                println!(
                    "decode emitted: {}x{} len={}",
                    f.width,
                    f.height,
                    f.data.len()
                );
                frames.push(f.data);
            }
            Ok(None) => break,
            Err(e) => {
                println!("decode error: {e:?}");
                break;
            }
        }
    }

    // Drain any remaining frames from the DPB.
    match dec.flush() {
        Ok(flushed) => {
            for f in &flushed {
                println!(
                    "flush emitted: {}x{} len={}",
                    f.width,
                    f.height,
                    f.data.len()
                );
                frames.push(f.data.clone());
            }
        }
        Err(e) => println!("flush error: {e:?}"),
    }

    println!("total emitted frames: {}", frames.len());

    // Compare against ffmpeg reference on a per-frame basis.
    if !frames.is_empty() && !ref_yuv.is_empty() {
        let n = frames.len().min(ref_frames);
        for (i, frame) in frames.iter().enumerate().take(n) {
            // PAFF flush can emit a field-sized frame; skip mismatched sizes
            // rather than panicking on the slice below.
            if frame.len() != frame_len {
                println!("frame#{i}: SKIP (size {} != {frame_len})", frame.len());
                continue;
            }
            let off = i * frame_len;
            let (max_d, n_d, tot) = compare(frame, &ref_yuv[off..off + frame_len]);
            let luma_n = (frame_len * 2) / 3;
            let (ld, ln, _) = compare(&frame[..luma_n], &ref_yuv[off..off + luma_n]);
            let (cd, cn, _) = compare(&frame[luma_n..], &ref_yuv[off + luma_n..off + frame_len]);
            println!(
                "frame#{i}: max_diff={max_d} diff={n_d}/{tot} | LUMA d={ld} n={ln} | CHROMA d={cd} n={cn}"
            );

            // Per-field (even rows = top, odd = bottom) luma max + per-field-MB grid.
            let (w, hh) = (80usize, 64usize);
            let mut fmax = [0i32; 2];
            for y in 0..hh {
                for x in 0..w {
                    let d = (frame[y * w + x] as i32 - ref_yuv[off + y * w + x] as i32).abs();
                    fmax[y & 1] = fmax[y & 1].max(d);
                }
            }
            println!(
                "  TOP(field0) luma max={} | BOT(field1) luma max={}",
                fmax[0], fmax[1]
            );
            if i == 0 {
                for fy in 0..16usize {
                    let y = 2 * fy + 1; // bottom field
                    let d: Vec<i32> = (48..80)
                        .map(|x| frame[y * w + x] as i32 - ref_yuv[off + y * w + x] as i32)
                        .collect();
                    if d.iter().any(|v| *v != 0) {
                        println!("  BOT fy={fy:2} x48..79 diff={d:?}");
                    }
                }
            }
            // Chroma (Cb) per-field-MB grid.
            let luma_all = w * hh;
            for (par, name) in [(0usize, "TOP"), (1, "BOT")] {
                print!("  {name} Cb grid:");
                for mbr in 0..2 {
                    print!(" [");
                    for mbc in 0..5 {
                        let mut m = 0i32;
                        for yy in 0..8usize {
                            let fy = mbr * 8 + yy;
                            let y = 2 * fy + par;
                            for xx in 0..8 {
                                let x = mbc * 8 + xx;
                                let o = luma_all + y * (w / 2) + x;
                                let d = (frame[o] as i32 - ref_yuv[off + o] as i32).abs();
                                m = m.max(d);
                            }
                        }
                        print!("{m:4}");
                    }
                    print!(" ]");
                }
                println!();
            }
            for (par, name) in [(0usize, "TOP"), (1, "BOT")] {
                print!("  {name} MB grid:");
                for mbr in 0..2 {
                    let mut s = String::new();
                    for mbc in 0..5 {
                        let mut m = 0i32;
                        for yy in 0..16 {
                            let fy = mbr * 16 + yy;
                            let y = 2 * fy + par;
                            for xx in 0..16 {
                                let x = mbc * 16 + xx;
                                let d = (frame[y * w + x] as i32 - ref_yuv[off + y * w + x] as i32)
                                    .abs();
                                m = m.max(d);
                            }
                        }
                        s.push_str(&format!("{m:4}"));
                    }
                    print!("  [{s} ]");
                }
                println!();
            }
        }
    }
}
