//! Phase G.5 PAFF corpus validation — all-intra isolation (todo-h264.md).
//!
//! Decodes an all-intra PAFF bitstream (generated by the JM reference encoder)
//! and compares against ffmpeg's reference decode. Uses an all-intra stream to
//! isolate field reconstruction (intra prediction, deblocking, interleaving)
//! from reference-list bugs — no inter prediction or ref lists are exercised.
//!
//! The test fixture is a 4-frame all-intra sequence encoded with
//! `PicInterlace=1` (field coding), `IntraPeriod=1`, `IDRPeriod=1`: every
//! field is an I-slice. ffmpeg outputs 4 frames in display order; the decoder
//! should match.

use std::process::Command;

use tpt_kinetix_core::packet::Packet;
use tpt_kinetix_core::timestamp::Timestamp;
use tpt_kinetix_h264::H264Decoder;

fn ffmpeg_available() -> bool {
    Command::new("ffmpeg")
        .arg("-version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

fn compare(a: &[u8], b: &[u8]) -> (i32, usize, usize) {
    let n = a.len().min(b.len());
    let mut max_diff = 0i32;
    let mut num_diff = 0usize;
    for i in 0..n {
        let d = (a[i] as i32 - b[i] as i32).abs();
        if d != 0 {
            num_diff += 1;
            max_diff = max_diff.max(d);
        }
    }
    (max_diff, num_diff, n)
}

fn make_packet(data: Vec<u8>, pts: i64) -> Packet {
    Packet {
        pts: Timestamp::new(pts, (1, 30)),
        dts: Timestamp::new(pts, (1, 30)),
        data,
        stream_index: 0,
        is_key_frame: true,
    }
}

#[test]
fn paff_i_fields_decode() {
    if !ffmpeg_available() {
        eprintln!("paff_i_fields_decode: skipped (ffmpeg unavailable)");
        return;
    }

    let dir = std::env::temp_dir().join("dbg_paff_i_fields");
    std::fs::create_dir_all(&dir).unwrap();

    let h264_path = dir.join("paff_i.h264");
    let ref_path = dir.join("paff_i_ref.yuv");

    let src = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("paff_i_fields.264");
    if !src.exists() {
        eprintln!("paff_i_fields_decode: fixture not found at {src:?}");
        return;
    }
    std::fs::copy(&src, &h264_path).unwrap();

    let ok = Command::new("ffmpeg")
        .args([
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-i",
            h264_path.to_str().unwrap(),
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p",
            ref_path.to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert!(ok.status.success(), "ffmpeg ref decode failed");
    let ref_yuv = std::fs::read(&ref_path).unwrap();
    let frame_len = 80 * 64 * 3 / 2;
    let ref_frames = ref_yuv.len() / frame_len;
    println!("ref_yuv: {} bytes ({} frames)", ref_yuv.len(), ref_frames);

    let annexb = std::fs::read(&h264_path).unwrap();

    let mut dec = H264Decoder::new();
    let pkt = make_packet(annexb, 0);
    let mut frames = Vec::new();

    match dec.decode(&pkt) {
        Ok(Some(f)) => {
            println!("decode emitted: {}x{} len={}", f.width, f.height, f.data.len());
            frames.push(f.data);
        }
        Ok(None) => println!("decode: no frame emitted"),
        Err(e) => println!("decode error: {e:?}"),
    }

    match dec.flush() {
        Ok(flushed) => {
            for f in &flushed {
                println!("flush emitted: {}x{} len={}", f.width, f.height, f.data.len());
                frames.push(f.data.clone());
            }
        }
        Err(e) => println!("flush error: {e:?}"),
    }

    println!("total emitted frames: {}", frames.len());
    assert_eq!(
        frames.len(),
        ref_frames,
        "frame count mismatch: decoded {} vs ref {}",
        frames.len(),
        ref_frames
    );

    if !frames.is_empty() && !ref_yuv.is_empty() {
        let n = frames.len().min(ref_frames);
        for i in 0..n {
            if frames[i].len() != frame_len {
                println!("frame#{i}: SKIP (size {} != {frame_len})", frames[i].len());
                continue;
            }
            let off = i * frame_len;
            let (max_d, n_d, tot) = compare(&frames[i], &ref_yuv[off..off + frame_len]);
            let luma_n = (frame_len * 2) / 3;
            let (ld, ln, _) = compare(&frames[i][..luma_n], &ref_yuv[off..off + luma_n]);
            let (cd, cn, _) = compare(&frames[i][luma_n..], &ref_yuv[off + luma_n..off + frame_len]);
            println!(
                "frame#{i}: max_diff={max_d} diff={n_d}/{tot} | LUMA d={ld} n={ln} | CHROMA d={cd} n={cn}"
            );
        }
    }
}
