use tpt_kinetix_core::{frame::VideoFrame, pixel_format::PixelFormat, timestamp::Timestamp};

/// Build a YUV420p `VideoFrame` where every sample is set to `value`.
fn yuv420p_frame_filled(width: u32, height: u32, y: u8, u: u8, v: u8) -> VideoFrame {
    let luma_size = (width as usize) * (height as usize);
    let chroma_size = (width as usize).div_ceil(2) * (height as usize).div_ceil(2);
    let mut data = Vec::with_capacity(luma_size + 2 * chroma_size);
    data.resize(luma_size, y);
    data.resize(luma_size + chroma_size, u);
    data.resize(luma_size + 2 * chroma_size, v);
    VideoFrame {
        pts: Timestamp::new(0, (1, 90_000)),
        dts: Timestamp::new(0, (1, 90_000)),
        data,
        width,
        height,
        pixel_format: PixelFormat::Yuv420p,
        is_key_frame: true,
    }
}

/// Returns a YUV420p frame with all samples set to 128 (mid-grey).
pub fn grey_yuv420p_frame(width: u32, height: u32) -> VideoFrame {
    yuv420p_frame_filled(width, height, 128, 128, 128)
}

/// Returns a YUV420p frame where the Y (luma) plane ramps from 0 (left) to 255
/// (right) across the width, and both chroma planes are set to 128.
pub fn ramp_yuv420p_frame(width: u32, height: u32) -> VideoFrame {
    let luma_size = (width as usize) * (height as usize);
    let chroma_size = (width as usize).div_ceil(2) * (height as usize).div_ceil(2);
    let mut data = Vec::with_capacity(luma_size + 2 * chroma_size);

    // Y plane: value ramps 0→255 based on the x-coordinate.
    for _row in 0..height {
        for col in 0..width {
            let val = if width <= 1 {
                0u8
            } else {
                ((col as u64 * 255) / (width as u64 - 1)) as u8
            };
            data.push(val);
        }
    }
    // Cb and Cr planes: constant 128.
    data.resize(luma_size + 2 * chroma_size, 128u8);

    VideoFrame {
        pts: Timestamp::new(0, (1, 90_000)),
        dts: Timestamp::new(0, (1, 90_000)),
        data,
        width,
        height,
        pixel_format: PixelFormat::Yuv420p,
        is_key_frame: true,
    }
}

/// Builds a minimal H.264 Annex B byte stream containing a hard-coded SPS + PPS for
/// a 16×16 baseline H.264 stream.  The SPS RBSP is bit-exact for a 16×16
/// baseline (profile_idc=66) Level 1.0 stream and parses to 16×16 dimensions.
pub fn minimal_h264_annexb_sps_pps() -> Vec<u8> {
    // SPS NAL unit (nal_unit_type = 7). Bytes were generated by bit-packing the
    // SPS syntax (Section 7.3.2.1) for:
    //   profile_idc=66, level_idc=10, seq_parameter_set_id=0,
    //   log2_max_frame_num_minus4=0, pic_order_cnt_type=0,
    //   log2_max_pic_order_cnt_lsb_minus4=0, max_num_ref_frames=1,
    //   gaps_in_frame_num_value_allowed_flag=0, pic_width_in_mbs_minus1=0,
    //   pic_height_in_map_units_minus1=0, frame_mbs_only_flag=1,
    //   direct_8x8_inference_flag=0, frame_cropping_flag=0,
    //   vui_parameters_present_flag=0
    // => 16×16 luma.
    let sps: &[u8] = &[0x67, 0x42, 0x00, 0x0A, 0xF4, 0xE2];

    // PPS NAL unit (nal_unit_type = 8)
    // pic_parameter_set_id=0, seq_parameter_set_id=0,
    // entropy_coding_mode_flag=0, pic_order_present_flag=0,
    // num_slice_groups_minus1=0, num_ref_idx_l0_active_minus1=0,
    // num_ref_idx_l1_active_minus1=0, weighted_pred_flag=0,
    // weighted_bipred_idc=0, pic_init_qp_minus26=0,
    // pic_init_qs_minus26=0, chroma_qp_index_offset=0,
    // deblocking_filter_control_present_flag=1, constrained_intra_pred_flag=0,
    // redundant_pic_cnt_present_flag=0
    let pps: &[u8] = &[
        0x68, // forbidden_zero=0, nal_ref_idc=3, nal_unit_type=8
        0xCE, 0x38, 0x80,
    ];

    let mut out = Vec::new();
    // SPS
    out.extend_from_slice(&[0x00, 0x00, 0x00, 0x01]);
    out.extend_from_slice(sps);
    // PPS
    out.extend_from_slice(&[0x00, 0x00, 0x00, 0x01]);
    out.extend_from_slice(pps);
    out
}

/// Builds a minimal ISO BMFF `ftyp` box with the `isom` major brand.
///
/// Box layout (20 bytes total):
/// ```text
/// 4 bytes: box size (big-endian u32) = 20
/// 4 bytes: box type = b"ftyp"
/// 4 bytes: major_brand = b"isom"
/// 4 bytes: minor_version = 0x00000200
/// 4 bytes: compatible_brands[0] = b"isom"
/// ```
pub fn synthetic_mp4_ftyp_box() -> Vec<u8> {
    let mut out = Vec::with_capacity(20);
    // size
    out.extend_from_slice(&20u32.to_be_bytes());
    // type
    out.extend_from_slice(b"ftyp");
    // major_brand
    out.extend_from_slice(b"isom");
    // minor_version
    out.extend_from_slice(&0x0000_0200u32.to_be_bytes());
    // compatible_brands
    out.extend_from_slice(b"isom");
    out
}

/// Generate a tiny AV1 bitstream in IVF container form using `ffmpeg`'s AV1
/// encoder, so the `dav1d` reference harness has real, decodeable input to run
/// against.
///
/// Returns `None` if `ffmpeg` is unavailable or the encode fails. The produced
/// stream is a short `testsrc` clip at the given dimensions.
pub fn minimal_av1_ivf() -> Option<Vec<u8>> {
    use std::{
        io::Read,
        process::{Command, Stdio},
    };

    let mut child = Command::new("ffmpeg")
        .args([
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=128x96:rate=15:duration=2",
            "-c:v",
            "av1",
            "-pix_fmt",
            "yuv420p",
            "-f",
            "ivf",
            "-",
        ])
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;

    let mut out = Vec::new();
    let read = child.stdout.take()?.read_to_end(&mut out).is_ok();
    let _ = child.wait();
    if !read || out.is_empty() {
        None
    } else {
        Some(out)
    }
}

/// Generate a multi-frame AV1 bitstream in **IVF** container form using
/// `ffmpeg`'s AV1 encoder, so inter-prediction (AV1 Phase E) can be validated
/// against a `dav1d` reference decode. The clip is a moving `testsrc` (so
/// non-key frames actually carry motion / inter blocks), `gop_size` apart from
/// one another, with `frames` total frames at the given dimensions.
///
/// Returns `None` if `ffmpeg` is unavailable or the encode fails. The produced
/// IVF is directly splittable by [`crate::reference::split_ivf_frames`] into per-frame
/// OBU payloads for feeding the Kinetix `tpt_kinetix_av1::Av1Decoder`
/// frame-by-frame.
pub fn minimal_av1_inter_ivf(frames: u32, width: u32, height: u32) -> Option<Vec<u8>> {
    use std::{
        io::Read,
        process::{Command, Stdio},
    };

    let src = format!("testsrc=size={width}x{height}:rate=15:duration={frames}");
    let mut child = Command::new("ffmpeg")
        .args([
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            &src,
            "-frames:v",
            &frames.to_string(),
            "-g",
            "10",
            "-c:v",
            "av1",
            "-pix_fmt",
            "yuv420p",
            "-f",
            "ivf",
            "-",
        ])
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;

    let mut out = Vec::new();
    let read = child.stdout.take()?.read_to_end(&mut out).is_ok();
    let _ = child.wait();
    if !read || out.is_empty() {
        None
    } else {
        Some(out)
    }
}

/// Generate a tiny AV1 bitstream in **OBU** form (section 5 low-overhead
/// bitstream) using `ffmpeg`'s AV1 encoder, so both the Kinetix
/// `tpt_kinetix_av1::Av1Decoder` (which consumes OBU bytes directly) and the
/// `ffmpeg`-backed reference decoder (`reference::decode_av1_with_ffmpeg`,
/// which also takes OBU bytes) can decode the same input.
///
/// Returns `None` if `ffmpeg` is unavailable or the encode fails. The produced
/// stream is a single `testsrc` keyframe at the given dimensions.
pub fn minimal_av1_obu(width: u32, height: u32) -> Option<Vec<u8>> {
    use std::{
        io::Read,
        process::{Command, Stdio},
    };

    let src = format!("testsrc=size={width}x{height}:rate=1:duration=1");
    let mut child = Command::new("ffmpeg")
        .args([
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            &src,
            "-frames:v",
            "1",
            "-c:v",
            "av1",
            "-pix_fmt",
            "yuv420p",
            "-f",
            "obu",
            "-",
        ])
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;

    let mut out = Vec::new();
    let read = child.stdout.take()?.read_to_end(&mut out).is_ok();
    let _ = child.wait();
    if !read || out.is_empty() {
        None
    } else {
        Some(out)
    }
}

/// One entry in [`av1_intra_corpus`]: a label, declared frame geometry, and
/// the raw OBU bytes of a single synthesized AV1 intra keyframe.
pub struct Av1CorpusEntry {
    pub label: &'static str,
    pub width: u32,
    pub height: u32,
    pub obu: Vec<u8>,
}

/// One entry in [`av1_inter_corpus`]: a label, declared frame geometry, and the
/// raw OBU bytes of a short synthesized AV1 **inter** clip (keyframe followed by
/// several motion-predicted frames, so the decoder must exercise MV prediction
/// and motion compensation, AV1 Phase E).
pub struct Av1InterCorpusEntry {
    pub label: &'static str,
    pub width: u32,
    pub height: u32,
    /// The full low-overhead-bitstream OBU of the whole clip (sequence header +
    /// every frame). The conformance harness splits this into per-frame packet
    /// bytes so the decoder builds up its reference-frame buffer frame-by-frame.
    pub obu: Vec<u8>,
    /// Number of frames in the clip (keyframe + inter).
    pub frames: usize,
}

/// Generate a short multi-frame AV1 OBU stream (keyframe + inter frames) with
/// `ffmpeg`'s AV1 encoder, so MV prediction / motion compensation (AV1 Phase E)
/// can be validated against a reference decoder. Returns `None` if `ffmpeg` is
/// unavailable or the encode fails.
///
/// The clip uses a moving `lavfi` source (`testsrc`) so successive frames
/// actually differ and the inter path is exercised. `frames` controls the clip
/// length.
pub fn av1_multiframe_obu(width: u32, height: u32, frames: u32) -> Option<Vec<u8>> {
    use std::{
        io::Read,
        process::{Command, Stdio},
    };

    let src = format!("testsrc=size={width}x{height}:rate=15:duration={frames}");
    let mut child = Command::new("ffmpeg")
        .args([
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            &src,
            "-frames:v",
            &frames.to_string(),
            "-c:v",
            "av1",
            "-pix_fmt",
            "yuv420p",
            "-f",
            "obu",
            "-",
        ])
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;

    let mut out = Vec::new();
    let read = child.stdout.take()?.read_to_end(&mut out).is_ok();
    let _ = child.wait();
    if !read || out.is_empty() {
        None
    } else {
        Some(out)
    }
}

/// One entry in [`av1_feature_corpus`]: a label, declared frame geometry, the
/// OBU bytes of the clip, and a human-readable description of the AV1 coding
/// tools the encoder was told to exercise for that entry.
pub struct Av1FeatureCorpusEntry {
    pub label: &'static str,
    /// The coding tools this entry is meant to exercise (for reporting).
    pub tools: &'static str,
    pub width: u32,
    pub height: u32,
    pub obu: Vec<u8>,
    /// Number of frame OBUs in the clip (keyframe + inter).
    pub frames: usize,
}

/// Count the frame OBUs (type 6) in a low-overhead bitstream, stopping at the
/// first temporal delimiter / sequence header boundary. Shared by
/// [`av1_inter_corpus`] and [`av1_feature_corpus`].
fn count_frame_obus(obu: &[u8]) -> usize {
    let mut count = 0usize;
    let mut pos = 0usize;
    while pos < obu.len() {
        if obu[pos] & 0x80 != 0 {
            break;
        }
        let header = obu[pos];
        let obu_type = (header >> 3) & 0x0f;
        let ext = header & 0x07 == 0x04;
        let has_size = header & 0x02 != 0;
        let mut off = pos + 1 + usize::from(ext);
        if off >= obu.len() {
            break;
        }
        let payload_len = if has_size {
            let mut i = 0usize;
            let mut size = 0usize;
            loop {
                if off + i >= obu.len() {
                    break;
                }
                let b = obu[off + i];
                size |= ((b & 0x7f) as usize) << (i * 7);
                i += 1;
                if b & 0x80 == 0 {
                    break;
                }
            }
            off += i;
            size
        } else {
            obu.len() - off
        };
        if obu_type == 6 {
            count += 1;
        }
        let end = off + payload_len;
        if end <= pos {
            break;
        }
        pos = end;
    }
    count
}

/// Generate a small corpus of short AV1 inter clips (keyframe + motion-predicted
/// frames) covering a few resolutions, for validating inter-prediction decode
/// (AV1 Phase E) against a reference decoder. Entries whose encode fails (e.g.
/// `ffmpeg` missing) are silently omitted; callers should treat an empty corpus
/// as "skip this test".
pub fn av1_inter_corpus() -> Vec<Av1InterCorpusEntry> {
    // 160x90 has a height that is neither 16- nor 8-aligned (90 = 8*11 + 2),
    // which stresses bottom/superblock-edge sub-8x8 splits; smptebars is
    // near-static, producing skip-heavy inter frames.
    const SOURCES: &[(&str, u32, u32, u32)] = &[
        ("testsrc_128x96", 128, 96, 8),
        ("testsrc_96x64", 96, 64, 6),
        ("testsrc_64x64", 64, 64, 6),
        ("testsrc_160x90", 160, 90, 8),
        ("smptebars_96x64", 96, 64, 6),
    ];

    SOURCES
        .iter()
        .filter_map(|&(label, width, height, frames)| {
            let obu = av1_multiframe_obu(width, height, frames)?;
            // Count Frame OBUs in the produced stream for the harness.
            let frames = count_frame_obus(&obu);
            if frames < 2 {
                return None;
            }
            Some(Av1InterCorpusEntry {
                label,
                width,
                height,
                obu,
                frames,
            })
        })
        .collect()
}

/// Encode a short AV1 clip with an explicit `lavfi` source and an extra set of
/// encoder arguments, returning the raw OBU bytes.
///
/// This is the parameterised form of [`av1_multiframe_obu`]: the existing
/// corpus generators all use ffmpeg's *default* AV1 encoder settings, which
/// means every entry exercises the same (conservative) subset of coding tools.
/// [`av1_feature_corpus`] uses this to deliberately turn individual tools on
/// (tiles, lossless, intrabc, restoration, angle delta, CFL, filter intra,
/// palette, extended/64-point transforms, ...) so the decoder's coverage of
/// each tool is measured rather than assumed.
///
/// Returns `None` if `ffmpeg` is unavailable or the encode fails (which is how
/// a tool the local libaom build refuses is handled — the entry is then simply
/// dropped from the corpus).
pub fn av1_feature_obu(
    lavfi_filter: &str,
    width: u32,
    height: u32,
    frames: u32,
    encoder_args: &[&str],
) -> Option<Vec<u8>> {
    use std::{
        io::Read,
        process::{Command, Stdio},
    };

    let src = format!("{lavfi_filter}=size={width}x{height}:rate=15:duration={frames}");
    let frames_str = frames.to_string();
    let mut args: Vec<String> = vec![
        "-loglevel".into(),
        "error".into(),
        "-f".into(),
        "lavfi".into(),
        "-i".into(),
        src,
        "-frames:v".into(),
        frames_str,
        "-pix_fmt".into(),
        "yuv420p".into(),
    ];
    args.extend(encoder_args.iter().map(|s| (*s).to_string()));
    args.extend([
        "-c:v".to_string(),
        "av1".to_string(),
        "-f".to_string(),
        "obu".to_string(),
        "-".to_string(),
    ]);

    let mut child = Command::new("ffmpeg")
        .args(&args)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;

    let mut out = Vec::new();
    let read = child.stdout.take()?.read_to_end(&mut out).is_ok();
    let _ = child.wait();
    if !read || out.is_empty() {
        None
    } else {
        Some(out)
    }
}

/// One row of the [`av1_feature_corpus`] table: label, the coding tools it
/// exercises, the encoder arguments that enable them, and the clip geometry.
/// A named type keeps the table's tuple readable (and keeps clippy's
/// `type_complexity` lint satisfied).
type Av1FeatureSpec = (
    &'static str,
    &'static str,
    &'static [&'static str],
    u32,
    u32,
    u32,
);

/// Generate a corpus of short AV1 clips that each deliberately exercise a
/// specific AV1 coding tool, so the decoder's per-tool coverage is measured
/// rather than assumed.
///
/// Every entry in [`av1_inter_corpus`] is encoded with ffmpeg's default AV1
/// encoder settings, so a decoder can pass that whole corpus while still having
/// no intrabc, restoration, palette, filter-intra, angle-delta, CFL, tiled or
/// extended-transform support at all — the tools simply never get used. This
/// corpus turns each of them on explicitly.
///
/// Entries whose encode fails (tool unavailable in the local libaom build, or
/// `ffmpeg` missing) are silently omitted; callers should treat an empty corpus
/// as "skip this test".
pub fn av1_feature_corpus() -> Vec<Av1FeatureCorpusEntry> {
    // `testsrc2` is the richest synthetic source (sharp glyph-like edges and
    // gradients) and is what makes the encoder's RD decisions actually pick
    // angle-delta / CFL / filter-intra / palette over plain DC.
    //
    // NOTE: several of these flags are *already* on by default in libaom
    // (angle-delta, CFL, filter-intra, 1:4 and rectangular partitions, idtx,
    // tx64, global motion all encode to byte-identical output with and without
    // the flag). That is fine and in fact useful: it means those entries are
    // byte-identical to a default-settings encode, so a gap reported for them
    // is a real default-path bug rather than an exotic-tool gap. The entries
    // that *do* change the bitstream are the ones that genuinely exercise a
    // distinct code path (tiles, lossless, intrabc, restoration, CDEF off).
    const SOURCES: &[Av1FeatureSpec] = &[
        (
            "tiles_2x2",
            "tiles",
            &["-tile-columns", "1", "-tile-rows", "1"],
            160,
            96,
            4,
        ),
        (
            "lossless",
            "lossless",
            &["-crf", "0", "-lossless", "1"],
            96,
            64,
            3,
        ),
        (
            "intrabc",
            "intra block copy",
            &["-enable-intrabc", "1", "-usage", "allintra"],
            320,
            180,
            2,
        ),
        (
            "restoration",
            "loop restoration",
            &["-enable-restoration", "1"],
            128,
            128,
            3,
        ),
        (
            "angle_delta",
            "angle delta intra",
            &["-enable-angle-delta", "1"],
            128,
            96,
            2,
        ),
        (
            "cfl_intra",
            "chroma-from-luma",
            &["-enable-cfl-intra", "1"],
            128,
            96,
            2,
        ),
        (
            "filter_intra",
            "filter intra",
            &["-enable-filter-intra", "1"],
            128,
            96,
            2,
        ),
        ("palette", "palette", &["-enable-palette", "1"], 64, 64, 2),
        (
            "flip_idtx",
            "extended transform type",
            &["-enable-flip-idtx", "1"],
            128,
            96,
            2,
        ),
        (
            "tx64",
            "64-point transform",
            &["-enable-tx64", "1"],
            128,
            128,
            2,
        ),
        (
            "rect_partitions",
            "rectangular / 1:4 partitions",
            &[
                "-enable-rect-partitions",
                "1",
                "-enable-1to4-partitions",
                "1",
            ],
            128,
            96,
            2,
        ),
        (
            "cdef_off",
            "CDEF disabled",
            &["-enable-cdef", "0", "-crf", "40"],
            128,
            96,
            2,
        ),
        (
            "global_motion",
            "global motion / warp",
            &["-enable-global-motion", "1", "-cpu-used", "0"],
            128,
            96,
            4,
        ),
        (
            "ref_frame_mvs",
            "temporal MV prediction",
            &[
                "-enable-ref-frame-mvs",
                "1",
                "-lag-in-frames",
                "2",
                "-cpu-used",
                "0",
            ],
            128,
            96,
            5,
        ),
    ];

    SOURCES
        .iter()
        .filter_map(|&(label, tools, enc, width, height, frames)| {
            let obu = av1_feature_obu("testsrc2", width, height, frames, enc)?;
            let count = count_frame_obus(&obu);
            if count < 1 {
                return None;
            }
            Some(Av1FeatureCorpusEntry {
                label,
                tools,
                width,
                height,
                obu,
                frames: count,
            })
        })
        .collect()
}

/// Generate a small corpus of single-keyframe AV1 OBU streams covering a
/// spread of content patterns and resolutions, for validating intra-only
/// decode (AV1 Phases A-C) against a reference decoder across more than one
/// sample.
///
/// Each entry is produced the same way as [`minimal_av1_obu`] (a single
/// `-frames:v 1` keyframe encoded with `ffmpeg`'s AV1 encoder), so the output
/// is directly consumable by both `tpt_kinetix_av1::Av1Decoder` and
/// `reference::decode_av1_with_ffmpeg`/`reference::decode_av1_with_dav1d`.
/// Entries whose encode fails (e.g. `ffmpeg` missing) are silently omitted;
/// callers should treat an empty corpus as "skip this test".
pub fn av1_intra_corpus() -> Vec<Av1CorpusEntry> {
    const SOURCES: &[(&str, &str, Option<&str>, u32, u32)] = &[
        ("testsrc", "testsrc", None, 128, 96),
        ("testsrc2", "testsrc2", None, 96, 64),
        ("testsrc2_big", "testsrc2", None, 320, 180),
        ("smptebars", "smptebars", None, 64, 64),
        ("mandelbrot", "mandelbrot", None, 80, 64),
        ("solid_red", "color", Some("c=red"), 32, 32),
    ];

    SOURCES
        .iter()
        .filter_map(|&(label, filter, extra, width, height)| {
            let obu = encode_av1_obu_keyframe(filter, extra, width, height)?;
            Some(Av1CorpusEntry {
                label,
                width,
                height,
                obu,
            })
        })
        .collect()
}

/// Shared implementation behind [`minimal_av1_obu`] and [`av1_intra_corpus`]:
/// encode one `lavfi` source filter into a single AV1 OBU keyframe.
fn encode_av1_obu_keyframe(
    lavfi_filter: &str,
    extra_params: Option<&str>,
    width: u32,
    height: u32,
) -> Option<Vec<u8>> {
    use std::{
        io::Read,
        process::{Command, Stdio},
    };

    let src = match extra_params {
        Some(extra) => format!("{lavfi_filter}={extra}:size={width}x{height}:rate=1"),
        None => format!("{lavfi_filter}=size={width}x{height}:rate=1"),
    };
    let mut child = Command::new("ffmpeg")
        .args([
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            &src,
            "-frames:v",
            "1",
            "-c:v",
            "av1",
            "-pix_fmt",
            "yuv420p",
            "-f",
            "obu",
            "-",
        ])
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;

    let mut out = Vec::new();
    let read = child.stdout.take()?.read_to_end(&mut out).is_ok();
    let _ = child.wait();
    if !read || out.is_empty() {
        None
    } else {
        Some(out)
    }
}

/// Encode a short CAVLC baseline-profile H.264 clip with `ffmpeg`, returning
/// the raw Annex B bytestream (read from stdout, so no temp file is needed).
///
/// Returns `None` if `ffmpeg` is unavailable or the encode fails. The produced
/// stream uses `cabac=0` and the supplied `x264_params` fragment, and is the
/// same class of clip the per-crate `*_conformance.rs` tests decode against.
fn ffmpeg_encode_h264(
    width: u32,
    height: u32,
    frames: u32,
    x264_params: &str,
    gop: u32,
) -> Option<Vec<u8>> {
    use std::{
        io::Read,
        process::{Command, Stdio},
    };

    let input_spec = format!("testsrc=size={width}x{height}:rate=1:duration={frames}");
    let frames_str = frames.to_string();
    let gop_str = gop.to_string();
    let mut child = Command::new("ffmpeg")
        .args([
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            &input_spec,
            "-frames:v",
            &frames_str,
            "-c:v",
            "libx264",
            "-profile:v",
            "baseline",
            "-g",
            &gop_str,
            "-bf",
            "0",
            "-pix_fmt",
            "yuv420p",
            "-x264-params",
            x264_params,
            "-f",
            "h264",
            "-",
        ])
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;

    let mut out = Vec::new();
    let read = child.stdout.take()?.read_to_end(&mut out).is_ok();
    let _ = child.wait();
    if !read || out.is_empty() {
        None
    } else {
        Some(out)
    }
}

/// Generate a single-frame baseline CAVLC I-frame H.264 clip with `ffmpeg`.
///
/// When `disable_deblocking` is true the encoder sets `no-deblock=1` (which
/// actually sets `disable_deblocking_filter_idc=1`, unlike `deblock=0`). Returns
/// `None` if `ffmpeg` is unavailable.
pub fn generate_h264_cavlc_iframe_clip(
    width: u32,
    height: u32,
    disable_deblocking: bool,
) -> Option<Vec<u8>> {
    let params = if disable_deblocking {
        "cabac=0:ref=1:bframes=0:8x8dct=0:weightp=0:aud=0:no-deblock=1"
    } else {
        "cabac=0:ref=1:bframes=0:8x8dct=0:weightp=0:aud=0"
    };
    ffmpeg_encode_h264(width, height, 1, params, 1)
}

/// Generate a two-frame (IDR, P) baseline CAVLC H.264 clip with `ffmpeg`, using
/// `deblock_param` as the x264 deblocking fragment (e.g. `"no-deblock=1"` or
/// `"deblock=0"`). Returns `None` if `ffmpeg` is unavailable.
pub fn generate_h264_cavlc_ip_clip(
    width: u32,
    height: u32,
    deblock_param: &str,
) -> Option<Vec<u8>> {
    let params = format!(
        "cabac=0:ref=1:bframes=0:8x8dct=0:weightp=0:aud=0:{deblock_param}:keyint=2:min-keyint=2"
    );
    ffmpeg_encode_h264(width, height, 2, &params, 2)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn grey_frame_dimensions() {
        let f = grey_yuv420p_frame(64, 48);
        assert_eq!(f.width, 64);
        assert_eq!(f.height, 48);
        let expected = 64 * 48 + 2 * (32 * 24);
        assert_eq!(f.data.len(), expected);
    }

    #[test]
    fn ramp_frame_luma_values() {
        let f = ramp_yuv420p_frame(2, 1);
        // Y[0] = 0, Y[1] = 255
        assert_eq!(f.data[0], 0);
        assert_eq!(f.data[1], 255);
    }

    #[test]
    fn ftyp_box_size() {
        let b = synthetic_mp4_ftyp_box();
        assert_eq!(b.len(), 20);
        assert_eq!(&b[0..4], &[0, 0, 0, 20]);
        assert_eq!(&b[4..8], b"ftyp");
    }

    #[test]
    fn annexb_starts_with_start_code() {
        let b = minimal_h264_annexb_sps_pps();
        assert_eq!(&b[0..4], &[0x00, 0x00, 0x00, 0x01]);
    }
}
