[package]
name = "tpt-kinetix-vp9-fuzz"
version = "0.0.1"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
tpt-kinetix-vp9 = { path = ".." }
tpt-kinetix-core = { path = "../../tpt-kinetix-core" }

[[bin]]
name = "fuzz_vp9_frame"
path = "fuzz_targets/fuzz_vp9_frame.rs"
test = false
doc = false
