#!/usr/bin/env python3
"""Generate tpt-kinetix-av1/src/reconstruct/qm_tables.rs from dav1d's src/qm.c.

The AV1 quantizer matrices (spec Quantizer_Matrix[15][2][3344]) are normative
data; dav1d ships them split per transform size. Usage:
    gen_av1_qm.py <path/to/dav1d/src/qm.c> <out.rs>
"""
import re
import sys

src = open(sys.argv[1], encoding="utf-8").read()
out = [
    "// @generated by scripts/gen_av1_qm.py from dav1d's src/qm.c (BSD-2-Clause,",
    "// Copyright (c) 2018 VideoLAN and dav1d authors / Two Orioles, LLC).",
    "// AV1 quantizer matrices, indexed [qm_level][plane > 0][coefficient].",
    "// Naming follows dav1d: `QM_AxB` is the table dav1d uses for the transform",
    "// whose width/height are swapped (it stores coefficients transposed).",
    "",
]
names = []
for m in re.finditer(r"static const uint8_t (qm_tbl_(\d+)x(\d+))\[(?:15)?\]\[2\]\[(\d+)\] = \{(.*?)\n\};", src, re.S):
    name, a, b, n, body = m.groups()
    nums = [int(x) for x in re.findall(r"\b\d+\b", body)]
    n = int(n)
    assert len(nums) == 15 * 2 * n, (name, len(nums), 15 * 2 * n)
    rust = f"QM_{a}X{b}"
    names.append((rust, n))
    out.append(f"pub(super) static {rust}: [[[u8; {n}]; 2]; 15] = [")
    idx = 0
    for lvl in range(15):
        out.append("    [")
        for pl in range(2):
            row = nums[idx : idx + n]
            idx += n
            out.append("        [" + ", ".join(map(str, row)) + "],")
        out.append("    ],")
    out.append("];")
    out.append("")
open(sys.argv[2], "w", encoding="utf-8").write("\n".join(out))
print("wrote", len(names), "tables:", [n for n, _ in names])
