#!/usr/bin/env python3
"""Generate Rust default-CDF consts for tpt-kinetix-av1 from the AV1 spec
``10.additional.tables.md``.

The spec publishes every default CDF as a C-style initializer list fenced in a
``~~~~~ c`` block.  We locate each named table, extract the balanced-brace
block, and recursively parse it into nested integer lists, then emit a Rust
``pub static`` array whose shape is inferred from the nesting.

These tables are the *exact* default probabilities the AV1 arithmetic decoder
must start from (identical to every conformant encoder), so they are
transcribed verbatim from the spec rather than approximated.
"""
import re
import sys

# Tables we need for intra keyframe decoding (Phases C/D scaffolding).
TARGETS = [
    "Default_Partition_W8_Cdf",
    "Default_Partition_W16_Cdf",
    "Default_Partition_W32_Cdf",
    "Default_Partition_W64_Cdf",
    "Default_Partition_W128_Cdf",
    "Default_Intra_Frame_Y_Mode_Cdf",
    "Default_Y_Mode_Cdf",
    "Default_Uv_Mode_Cfl_Not_Allowed_Cdf",
    "Default_Uv_Mode_Cfl_Allowed_Cdf",
    "Default_Tx_8x8_Cdf",
    "Default_Tx_16x16_Cdf",
    "Default_Tx_32x32_Cdf",
    "Default_Tx_64x64_Cdf",
    "Default_Txfm_Split_Cdf",
    "Default_Skip_Cdf",
    "Default_Angle_Delta_Cdf",
    "Default_Interp_Filter_Cdf",
]

# Small non-CDF lookup tables are hardcoded in Rust (see reconstruct.rs);
# they are small, fixed, and not probability tables.
LOOKUP_TARGETS = []


def find_blocks(text):
    """Return dict name -> raw brace content (string inside outermost {})."""
    out = {}
    # Match:  Name[ ... ] = {  ...  };
    # We anchor on the name then scan for the first '{' and its matching '}'.
    for m in re.finditer(r"([A-Za-z_][A-Za-z0-9_]*)\s*\[", text):
        name = m.group(1)
        if name not in set(TARGETS) | set(LOOKUP_TARGETS):
            continue
        if name in out:
            continue
        # find '=' after this point
        eq = text.find("=", m.end())
        if eq == -1:
            continue
        # find first '{' after '='
        brace = text.find("{", eq)
        if brace == -1:
            continue
        # match braces
        depth = 0
        i = brace
        while i < len(text):
            c = text[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    out[name] = text[brace + 1 : i]
                    break
            i += 1
    return out


def parse_value(s, i):
    """Parse one value starting at index i. Returns (value, next_index).

    value is either an int or a list of values.
    """
    # skip whitespace and commas
    while i < len(s) and s[i] in " \t\r\n,":
        i += 1
    if i >= len(s):
        return None, i
    if s[i] == "{":
        lst = []
        i += 1
        while True:
            while i < len(s) and s[i] in " \t\r\n,":
                i += 1
            if i < len(s) and s[i] == "}":
                i += 1
                break
            v, i = parse_value(s, i)
            if v is None:
                break
            lst.append(v)
        return lst, i
    # integer
    m = re.match(r"-?\d+", s[i:])
    if not m:
        # skip a stray token (e.g. a comment start)
        j = i
        while j < len(s) and s[j] not in ",{} \t\r\n":
            j += 1
        return None, j
    return int(m.group(0)), i + m.end()


def to_rust_type(node):
    if isinstance(node, int):
        return "u16"
    # list
    elem = node[0] if node else 0
    inner = to_rust_type(elem)
    return f"[{inner}; {len(node)}]"


def to_rust_literal(node):
    if isinstance(node, int):
        return str(node)
    parts = [to_rust_literal(x) for x in node]
    return "[" + ", ".join(parts) + "]"


def fmt_rust(name, node, is_lookup):
    rust_name = name.upper()
    if is_lookup:
        # flat-ish int arrays (may be nested 2D)
        ty = to_rust_type(node).replace("u16", "u8" if max_int(node) < 256 else "u16")
        return f"pub static {rust_name}: {ty} = {to_rust_literal(node)};\n"
    ty = to_rust_type(node)
    return f"pub static {rust_name}: {ty} = {to_rust_literal(node)};\n"


def max_int(node):
    if isinstance(node, int):
        return node
    return max((max_int(x) for x in node), default=0)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "av1_tables.md"
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    blocks = find_blocks(text)

    lines = []
    lines.append("// @generated by scripts/gen_av1_cdf.py from AV1 spec 10.additional.tables.md\n")
    lines.append("// Exact default CDF / lookup tables. Do not edit by hand.\n")
    missing = []
    for name in TARGETS:
        if name not in blocks:
            missing.append(name)
            continue
        node, _ = parse_value("{" + blocks[name] + "}", 0)
        lines.append(fmt_rust(name, node, False))
    for name in LOOKUP_TARGETS:
        if name not in blocks:
            missing.append(name)
            continue
        node, _ = parse_value("{" + blocks[name] + "}", 0)
        lines.append(fmt_rust(name, node, True))
    if missing:
        sys.stderr.write("MISSING: " + ", ".join(missing) + "\n")
    out = "".join(lines)
    if len(sys.argv) > 2:
        with open(sys.argv[2], "w", encoding="utf-8") as f:
            f.write(out)
    else:
        sys.stdout.write(out)


if __name__ == "__main__":
    main()
