// Dumps the coefficient-relevant default tables + constants from this crate
// as a Python module (via `{:?}` debug formatting, which is valid Python list
// syntax). The resulting file is consumed by `tools/av1_oracle` to build an
// independent re-implementation of `coeffs()` whose *control flow* (context
// derivation + symbol read order) is hand-written from the spec, while the
// table *values* come from this crate. This guarantees the oracle's table data
// exactly matches what Kinetix decodes, so any divergence it finds against a
// real tile is a genuine control-flow / context bug (a table-value bug would
// need a spec-PDF re-transcription pass, tracked separately).
//
// Run: cargo run -p tpt-kinetix-av1 --example dump_oracle_tables > ../../tools/av1_oracle/cdf_tables_gen.py

use tpt_kinetix_av1::coeff_tables::*;
use tpt_kinetix_av1::entropy_cdf::*;

fn main() {
    println!("# Auto-generated by tpt-kinetix-av1/examples/dump_oracle_tables.rs");
    println!("# Coefficient tables/constants for the independent Python AV1 coeff oracle.\n");

    println!("TX_WIDTH = {:?}", TX_WIDTH);
    println!("TX_HEIGHT = {:?}", TX_HEIGHT);
    println!("TX_WIDTH_LOG2 = {:?}", TX_WIDTH_LOG2);
    println!("TX_HEIGHT_LOG2 = {:?}", TX_HEIGHT_LOG2);
    println!("TX_SIZE_SQR = {:?}", TX_SIZE_SQR);
    println!("TX_SIZE_SQR_UP = {:?}", TX_SIZE_SQR_UP);
    println!("ADJUSTED_TX_SIZE = {:?}", ADJUSTED_TX_SIZE);
    println!();
    println!("DCT_DCT = {:?}", DCT_DCT);
    println!("TX_CLASS_HORIZ = {:?}", TX_CLASS_HORIZ);
    println!("TX_CLASS_VERT = {:?}", TX_CLASS_VERT);
    println!("TX_CLASS_2D = {:?}", TX_CLASS_2D);
    println!("TX_SET_DCTONLY = {:?}", TX_SET_DCTONLY);
    println!("TX_SET_INTRA_1 = {:?}", TX_SET_INTRA_1);
    println!("TX_SET_INTRA_2 = {:?}", TX_SET_INTRA_2);
    println!("NUM_BASE_LEVELS = {:?}", NUM_BASE_LEVELS);
    println!("COEFF_BASE_RANGE = {:?}", COEFF_BASE_RANGE);
    println!("BR_CDF_SIZE = {:?}", BR_CDF_SIZE);
    println!("SIG_COEF_CONTEXTS = {:?}", SIG_COEF_CONTEXTS);
    println!("SIG_COEF_CONTEXTS_EOB = {:?}", SIG_COEF_CONTEXTS_EOB);
    println!("SIG_REF_DIFF_OFFSET = {:?}", SIG_REF_DIFF_OFFSET);
    println!(
        "MAG_REF_OFFSET_WITH_TX_CLASS = {:?}",
        MAG_REF_OFFSET_WITH_TX_CLASS
    );
    println!("COEFF_BASE_CTX_OFFSET = {:?}", COEFF_BASE_CTX_OFFSET);
    println!(
        "COEFF_BASE_POS_CTX_OFFSET = {:?}",
        COEFF_BASE_POS_CTX_OFFSET
    );
    println!("MODE_TO_TXFM = {:?}", MODE_TO_TXFM);
    println!("TX_TYPE_IN_SET_INTRA = {:?}", TX_TYPE_IN_SET_INTRA);
    println!("TX_TYPE_INTRA_INV_SET1 = {:?}", TX_TYPE_INTRA_INV_SET1);
    println!("TX_TYPE_INTRA_INV_SET2 = {:?}", TX_TYPE_INTRA_INV_SET2);
    println!();

    println!("DEFAULT_TXB_SKIP_CDF = {:?}", DEFAULT_TXB_SKIP_CDF);
    println!("DEFAULT_EOB_PT_16_CDF = {:?}", DEFAULT_EOB_PT_16_CDF);
    println!("DEFAULT_EOB_PT_32_CDF = {:?}", DEFAULT_EOB_PT_32_CDF);
    println!("DEFAULT_EOB_PT_64_CDF = {:?}", DEFAULT_EOB_PT_64_CDF);
    println!("DEFAULT_EOB_PT_128_CDF = {:?}", DEFAULT_EOB_PT_128_CDF);
    println!("DEFAULT_EOB_PT_256_CDF = {:?}", DEFAULT_EOB_PT_256_CDF);
    println!("DEFAULT_EOB_PT_512_CDF = {:?}", DEFAULT_EOB_PT_512_CDF);
    println!("DEFAULT_EOB_PT_1024_CDF = {:?}", DEFAULT_EOB_PT_1024_CDF);
    println!("DEFAULT_EOB_EXTRA_CDF = {:?}", DEFAULT_EOB_EXTRA_CDF);
    println!(
        "DEFAULT_COEFF_BASE_EOB_CDF = {:?}",
        DEFAULT_COEFF_BASE_EOB_CDF
    );
    println!("DEFAULT_COEFF_BASE_CDF = {:?}", DEFAULT_COEFF_BASE_CDF);
    println!("DEFAULT_COEFF_BR_CDF = {:?}", DEFAULT_COEFF_BR_CDF);
    println!("DEFAULT_DC_SIGN_CDF = {:?}", DEFAULT_DC_SIGN_CDF);
    println!(
        "DEFAULT_INTRA_TX_TYPE_SET1_CDF = {:?}",
        DEFAULT_INTRA_TX_TYPE_SET1_CDF
    );
    println!(
        "DEFAULT_INTRA_TX_TYPE_SET2_CDF = {:?}",
        DEFAULT_INTRA_TX_TYPE_SET2_CDF
    );
    println!();

    println!("# Precomputed scan tables: SCANS[(tx_size, tx_type)] = [raster positions]");
    print!("SCANS = {{");
    let mut first = true;
    for tx in 0..19usize {
        for ty in 0..16usize {
            if let Some(s) = get_scan(tx, ty) {
                if !first {
                    print!(", ");
                }
                first = false;
                print!("({tx}, {ty}): {:?}", s);
            }
        }
    }
    println!("}}");
    println!();

    println!("# Sanity: TileCdfs::q_context buckets exist for q in 0..256");
    println!(
        "# (q_context bucketing is reimplemented in Python; data above is the 4-q-indexed tables)"
    )
}
